In [2]:
import pandas as pd
import numpy as np

Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

data1 = patient data
data2 = billing data

In [3]:
data1 = pd.read_csv("Patient_Data.csv")

In [4]:
data2 = pd.read_csv("Billing_Data.csv")

### EDA of data1

In [5]:
data1.shape

(6, 7)

In [6]:
data1.size

42

In [7]:
data1.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [8]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [9]:
data1[['PatientID','Department','Doctor','BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [10]:
data1.drop(columns = ['ReceptionistID','CheckInTime'],inplace = True)

In [11]:
data1.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [12]:
data1.duplicated().sum()

np.int64(1)

In [13]:
data1.drop_duplicates(inplace = True)

In [14]:
data1.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    2
dtype: int64

In [15]:
data1.fillna(data1.BillAmount.mean(),inplace = True)

In [16]:
data1.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    0
dtype: int64

In [17]:
data1.groupby('Department')['BillAmount'].sum()

Department
Cardiology     11200.000000
Dermatology     6233.333333
Neurology       6233.333333
Orthopedics     7500.000000
Name: BillAmount, dtype: float64

### EDA of data2

In [18]:
data2.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [19]:
data2.duplicated().sum()

np.int64(0)

In [20]:
data2.isnull().sum()

PatientID           0
InsuranceCovered    0
FinalAmount         0
dtype: int64

7.	Merge the billing dataset with patient dataset on PatientID.

In [21]:
new_data = pd.merge(data1,data2,on = 'PatientID')

In [22]:
new_data.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

8. 8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [23]:
week_data = {
    'PatientID': [6, 7],
    'Name': ['Rahul', 'Amit']
}

In [24]:
df = pd.DataFrame(week_data)

In [31]:
new_df = pd.concat([data1, data2], axis=1).reset_index(drop=True)

In [32]:
new_df

,PatientID,Name,Department,Doctor,BillAmount,PatientID,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,101,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,102,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,103,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,104,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,105,1000,4000

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [27]:
week_data = {
    'InsuranceCovered': [6, 7],
    'FinalAmount': [9000, 4000]
}

In [28]:
df = pd.DataFrame(week_data)

In [29]:
new_df = pd.concat([data1, data2], axis=1).reset_index(drop=True)

In [30]:
new_df

,PatientID,Name,Department,Doctor,BillAmount,PatientID,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,101,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,102,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,103,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,104,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,105,1000,4000